# Generated by Django 6.0.3 on 2026-03-15 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='antecedentes',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='fecha_consulta',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='medicacion',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='motivo_consulta',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='procedimiento',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='resumen',
        ),
        migrations.AddField(
            model_name='expediente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.paciente'),
        ),
        migrations.CreateModel(
            name='AntecedentesHeredofamiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padre_vivo', models.BooleanField()),
                ('causa_muerte_padre', models.TextField(blank=True)),
                ('madre_viva', models.BooleanField()),
                ('causa_muerte_madre', models.TextField(blank=True)),
                ('hermanos_vivos', models.IntegerField(default=0)),
                ('hermanos_fallecidos', models.IntegerField(default=0)),
                ('causa_muerte_hermanos', models.TextField(blank=True)),
                ('hijos_vivos', models.IntegerField(default=0)),
                ('hijos_fallecidos', models.IntegerField(default=0)),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('tuberculosis', models.BooleanField(default=False)),
                ('cancer', models.BooleanField(default=False)),
                ('otras_enfermedades', models.TextField(blank=True)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesNoPatologicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol', models.BooleanField(default=False)),
                ('tabaco', models.BooleanField(default=False)),
                ('drogas', models.BooleanField(default=False)),
                ('alimentacion', models.TextField(blank=True)),
                ('dipsia', models.TextField(blank=True)),
                ('diuresis', models.TextField(blank=True)),
                ('catarsis', models.TextField(blank=True)),
                ('somnia', models.TextField(blank=True)),
                ('otros', models.TextField(blank=True)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesPatologicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('tuberculosis', models.BooleanField(default=False)),
                ('cancer', models.BooleanField(default=False)),
                ('otras', models.TextField(blank=True)),
                ('quirurgicos', models.TextField(blank=True)),
                ('traumatologicos', models.TextField(blank=True)),
                ('alergicos', models.TextField(blank=True)),
                ('otros', models.TextField(blank=True)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_presuntivo', models.TextField()),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='ExploracionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impresion_general', models.TextField()),
                ('fc', models.IntegerField(blank=True, null=True)),
                ('ta', models.CharField(max_length=20)),
                ('fr', models.IntegerField(blank=True, null=True)),
                ('pulso', models.IntegerField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('talla', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('inspeccion_general', models.TextField(blank=True)),
                ('cabeza', models.TextField(blank=True)),
                ('cuello', models.TextField(blank=True)),
                ('torax', models.TextField(blank=True)),
                ('abdomen', models.TextField(blank=True)),
                ('tacto_vaginal_rectal', models.TextField(blank=True)),
                ('extremidades', models.TextField(blank=True)),
                ('exploracion_neurologica', models.TextField(blank=True)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='FichaIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(max_length=150)),
                ('residencia', models.CharField(max_length=200)),
                ('estado_civil', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('cama', models.CharField(max_length=20)),
                ('servicio', models.CharField(max_length=100)),
                ('escolaridad', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='GinecoObstetricos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fum', models.DateField(blank=True, null=True)),
                ('fpp', models.DateField(blank=True, null=True)),
                ('edad_gestacional', models.IntegerField(blank=True, null=True)),
                ('menarca', models.IntegerField(blank=True, null=True)),
                ('ritmo_menstrual', models.CharField(blank=True, max_length=100)),
                ('numero_parejas', models.IntegerField(blank=True, null=True)),
                ('flujo_genital', models.TextField(blank=True)),
                ('gestas', models.IntegerField(default=0)),
                ('partos', models.IntegerField(default=0)),
                ('cesareas', models.IntegerField(default=0)),
                ('abortos', models.IntegerField(default=0)),
                ('anticonceptivos', models.BooleanField(default=False)),
                ('tipo_anticonceptivo', models.CharField(blank=True, max_length=100)),
                ('tiempo_anticonceptivo', models.CharField(blank=True, max_length=100)),
                ('ultima_toma', models.DateField(blank=True, null=True)),
                ('cirugias_ginecologicas', models.TextField(blank=True)),
                ('otros', models.TextField(blank=True)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='InterrogatorioSistemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respiratorio', models.TextField(blank=True)),
                ('digestivo', models.TextField(blank=True)),
                ('cardiovascular', models.TextField(blank=True)),
                ('renal_urinario', models.TextField(blank=True)),
                ('genital', models.TextField(blank=True)),
                ('endocrino', models.TextField(blank=True)),
                ('hematopoyetico', models.TextField(blank=True)),
                ('piel', models.TextField(blank=True)),
                ('musculo_esqueletico', models.TextField(blank=True)),
                ('sistema_nervioso', models.TextField(blank=True)),
                ('organos_sentidos', models.TextField(blank=True)),
                ('sintomas_generales', models.TextField(blank=True)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='PadecimientoActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTerapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.TextField()),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.expediente')),
            ],
        ),
    ]
